### ISSUE TITLE
This Week in Rails import script broken

### ISSUE THREAD

**Issue by andyatkinson** [rails/weblog#112]
Looks like the markup changed, so the import script is now broken. Didn't dig in much, but the initial CSS selector it's looking for "table.outer" isn't there, and we know Goodbits recently changed their UI experience, so maybe the markup changed as well.

To reproduce the problem, I ran the import script on the latest issue:

```$ ./_import-this-week-in-rails.rb https://rails-weekly.ongoodbits.com/2017/04/15/hooks-fixtures-fetch_values-database-connections-and-more```

**Comment by gregmolnar** [comment]
I am looking into this.

**Comment by gregmolnar** [comment]
There are no headings at all now, so it looks pretty tricky to parse the newsletter.

**Comment by andyatkinson** [comment]
@gregmolnar I agree. I asked Goodbits if they could add any more markup that we could use for the scraper, and explained that we're creating a Markdown file export. I figured it was worth a shot.

**Comment by gregmolnar** [comment]
@andyatkinson thanks for doing that! Hopefully they will do the change.

**Comment by kaspth** [comment]
Good thinking 👍( ͡° ͜ʖ ͡°)👍

**Comment by kalvir-sandhu** [comment]
Let me know if the approach I proposed in the PR will work for you guys.
