### ISSUE TITLE
Convert old blog posts to Markdown

### ISSUE THREAD

**Issue by maclover7** [rails/weblog#48]
According to @rafaelfranca, GitHub will no longer be supporting any GitHub Pages documents that are in the "Textile" format. There are between 900-1000 of such documents in this repo. I think I found a tool to convert them, so I'll try and take care of this over the upcoming weekend. :heart:

**Comment by rafaelfranca** [comment]
:+1:

**Comment by rafaelfranca** [comment]
https://github.com/blog/2115-upgrading-your-textile-posts-to-markdown

**Comment by matthewd** [comment]
As they're old blog posts (i.e., not destined to be edited), the other option would be to just convert to HTML... might be less likely to create conversion artifacts? ¯\_(ツ)_/¯
