### ISSUE TITLE
emojis not rendering in published

### ISSUE THREAD

**Issue by wyaeld** [rails/weblog#62]
@prathamesh-sonpatki

even though the emoji show up in the GFM display here 

https://github.com/rails/weblog/blob/gh-pages/_posts/2016-04-23-this-week-in-rails-speed-improvements-database-comments-and-more.markdown

they don't show up in the raw markdown
https://raw.githubusercontent.com/rails/weblog/gh-pages/_posts/2016-04-23-this-week-in-rails-speed-improvements-database-comments-and-more.markdown

or display correctly (at least to chrome on linux) when viewing the published weblog

**Comment by prathamesh-sonpatki** [comment]
Thanks @wyaeld Not sure why that happened? 

Can  you check some past newsletters also whether they get displayed properly in raw format?

It works for me on Mac and Chrome.

**Comment by wyaeld** [comment]
actually, if you haven't changed anything, it might be fonts missing on one
of my systems.

right now at home with windows + chrome, and it works.  However ubuntu
14.04 desktop did not.  Not sure what the font-family needs to be for
emojis.

**Comment by kaspth** [comment]
Is this still an issue? I'll close for now, thanks!
